alias cls=clear
alias s=sudo
alias cc="cargo check"
alias cr="cargo run"
alias v=nvim
alias ls=lsd
alias ll="lsd -l"
alias la="lsd -A"
alias l="lsd -Al"
alias saat="date '+%H:%M'"
alias cat=bat
alias rm=rip
